INSERT INTO sectors (code_value, code_text) VALUES (1, 'Manufacturing');
INSERT INTO sectors (code_value, code_text) VALUES (19, 'Construction materials');
INSERT INTO sectors (code_value, code_text) VALUES (18, 'Electronics and Optics');
INSERT INTO sectors (code_value, code_text) VALUES (6, 'Food and Beverage');
INSERT INTO sectors (code_value, code_text) VALUES (342, 'Bakery & confectionery products');
INSERT INTO sectors (code_value, code_text) VALUES (43, 'Beverages');
INSERT INTO sectors (code_value, code_text) VALUES (42, 'Fish & fish products');
INSERT INTO sectors (code_value, code_text) VALUES (40, 'Meat & meat products');
INSERT INTO sectors (code_value, code_text) VALUES (39, 'Milk & dairy products');
INSERT INTO sectors (code_value, code_text) VALUES (437, 'Other');
INSERT INTO sectors (code_value, code_text) VALUES (378, 'Sweets & snack food');
INSERT INTO sectors (code_value, code_text) VALUES (13, 'Furniture');
INSERT INTO sectors (code_value, code_text) VALUES (389, 'Bathroom/sauna');
INSERT INTO sectors (code_value, code_text) VALUES (385, 'Bedroom');
INSERT INTO sectors (code_value, code_text) VALUES (390, 'Children’s room');
INSERT INTO sectors (code_value, code_text) VALUES (98, 'Kitchen');
INSERT INTO sectors (code_value, code_text) VALUES (101, 'Living room');
INSERT INTO sectors (code_value, code_text) VALUES (392, 'Office');
INSERT INTO sectors (code_value, code_text) VALUES (394, 'Other (Furniture)');
INSERT INTO sectors (code_value, code_text) VALUES (341, 'Outdoor');
INSERT INTO sectors (code_value, code_text) VALUES (99, 'Project furniture');
INSERT INTO sectors (code_value, code_text) VALUES (12, 'Machinery');
INSERT INTO sectors (code_value, code_text) VALUES (94, 'Machinery components');
INSERT INTO sectors (code_value, code_text) VALUES (91, 'Machinery equipment/tools');
INSERT INTO sectors (code_value, code_text) VALUES (224, 'Manufacture of machinery');
INSERT INTO sectors (code_value, code_text) VALUES (97, 'Maritime');
INSERT INTO sectors (code_value, code_text) VALUES (271, 'Aluminium and steel workboats');
INSERT INTO sectors (code_value, code_text) VALUES (269, 'Boat/Yacht building');
INSERT INTO sectors (code_value, code_text) VALUES (230, 'Ship repair and conversion');
INSERT INTO sectors (code_value, code_text) VALUES (93, 'Metal structures');
INSERT INTO sectors (code_value, code_text) VALUES (508, 'Other');
INSERT INTO sectors (code_value, code_text) VALUES (227, 'Repair and maintenance service');
INSERT INTO sectors (code_value, code_text) VALUES (11, 'Metalworking');
INSERT INTO sectors (code_value, code_text) VALUES (67, 'Construction of metal structures');
INSERT INTO sectors (code_value, code_text) VALUES (263, 'Houses and buildings');
INSERT INTO sectors (code_value, code_text) VALUES (267, 'Metal products');
INSERT INTO sectors (code_value, code_text) VALUES (542, 'Metal works');
INSERT INTO sectors (code_value, code_text) VALUES (75, 'CNC-machining');
INSERT INTO sectors (code_value, code_text) VALUES (62, 'Forgings, Fasteners');
INSERT INTO sectors (code_value, code_text) VALUES (69, 'Gas, Plasma, Laser cutting');
INSERT INTO sectors (code_value, code_text) VALUES (66, 'MIG, TIG, Aluminum welding');
INSERT INTO sectors (code_value, code_text) VALUES (9, 'Plastic and Rubber');
INSERT INTO sectors (code_value, code_text) VALUES (54, 'Packaging');
INSERT INTO sectors (code_value, code_text) VALUES (556, 'Plastic goods');
INSERT INTO sectors (code_value, code_text) VALUES (559, 'Plastic processing technology');
INSERT INTO sectors (code_value, code_text) VALUES (55, 'Blowing');
INSERT INTO sectors (code_value, code_text) VALUES (57, 'Moulding');
INSERT INTO sectors (code_value, code_text) VALUES (53, 'Plastics welding and processing');
INSERT INTO sectors (code_value, code_text) VALUES (560, 'Plastic profiles');
INSERT INTO sectors (code_value, code_text) VALUES (5, 'Printing');
INSERT INTO sectors (code_value, code_text) VALUES (148, 'Advertising');
INSERT INTO sectors (code_value, code_text) VALUES (150, 'Book/Periodicals printing');
INSERT INTO sectors (code_value, code_text) VALUES (145, 'Labelling and packaging printing');
INSERT INTO sectors (code_value, code_text) VALUES (7, 'Textile and Clothing');
INSERT INTO sectors (code_value, code_text) VALUES (44, 'Clothing');
INSERT INTO sectors (code_value, code_text) VALUES (45, 'Textile');
INSERT INTO sectors (code_value, code_text) VALUES (8, 'Wood');
INSERT INTO sectors (code_value, code_text) VALUES (337, 'Other (Wood)');
INSERT INTO sectors (code_value, code_text) VALUES (51, 'Wooden building materials');
INSERT INTO sectors (code_value, code_text) VALUES (47, 'Wooden houses');
INSERT INTO sectors (code_value, code_text) VALUES (3, 'Other');
INSERT INTO sectors (code_value, code_text) VALUES (37, 'Creative industries');
INSERT INTO sectors (code_value, code_text) VALUES (29, 'Energy technology');
INSERT INTO sectors (code_value, code_text) VALUES (33, 'Environment');
INSERT INTO sectors (code_value, code_text) VALUES (2, 'Service');
INSERT INTO sectors (code_value, code_text) VALUES (25, 'Business services');
INSERT INTO sectors (code_value, code_text) VALUES (35, 'Engineering');
INSERT INTO sectors (code_value, code_text) VALUES (28, 'Information Technology and Telecommunications');
INSERT INTO sectors (code_value, code_text) VALUES (581, 'Data processing, Web portals, E-marketing');
INSERT INTO sectors (code_value, code_text) VALUES (576, 'Programming, Consultancy');
INSERT INTO sectors (code_value, code_text) VALUES (121, 'Software, Hardware');
INSERT INTO sectors (code_value, code_text) VALUES (122, 'Telecommunications');
INSERT INTO sectors (code_value, code_text) VALUES (22, 'Tourism');
INSERT INTO sectors (code_value, code_text) VALUES (141, 'Translation services');
INSERT INTO sectors (code_value, code_text) VALUES (21, 'Transport and Logistics');
INSERT INTO sectors (code_value, code_text) VALUES (111, 'Air');
INSERT INTO sectors (code_value, code_text) VALUES (114, 'Rail');
INSERT INTO sectors (code_value, code_text) VALUES (112, 'Road');
INSERT INTO sectors (code_value, code_text) VALUES (113, 'Water');
